@startuml BBショップ注文管理システム（支払情報登録）

actor 顧客 as customer
boundary カート一覧画面 as bCart
control 送付先情報入力画面表示 as cSenderEntryDisplay
boundary 送付先情報入力画面 as bSender
control 住所検索処理 as cSearchAddress
control 住所表示処理 as cDisplayAddress
entity 住所検索サービス as eAddress
control 送信先情報入力チェック as cSenderEntryCheck
control 送信先情報入力エラー画面表示 as cSenderEntryError
boundary 送付先情報入力エラー画面 as bSenderEntryError
control 送信先情報登録 as cCreateSender
entity 支払情報 as eSender
control 支払情報入力画面表示 as cPaymentEntryDisplay
boundary 支払情報入力画面 as bPaymentEntry


' 画面表示
customer -> bCart : 前画面より継続()
bCart -> cSenderEntryDisplay : ［注文する］をクリック()
cSenderEntryDisplay -> bSender : 表示()

' 住所検索
bSender -> cSearchAddress : 起動()
cSearchAddress -> eAddress : ※serchArressAPI(postNo)
eAddress -> cDisplayAddress : 応答()

' 送付先情報チェック
bSender -> cSenderEntryCheck : ［確定する］をクリック()
alt チェックOK
    cSenderEntryCheck -> cCreateSender : 起動()
    cCreateSender -> eSender : createSender()
    cCreateSender -> cPaymentEntryDisplay : 起動()
    cPaymentEntryDisplay -> bPaymentEntry : 表示()
    bPaymentEntry --> customer
else チェックNG
    cSenderEntryCheck -> cSenderEntryError : 起動()
    cSenderEntryError -> bSenderEntryError : 表示()
    bSenderEntryError --> customer :
end

@enduml